### ISSUE TITLE
Erob Test sometimes runs a little bit only.

### ISSUE THREAD

**Issue by Rohithossain007** [ZeroErrControl/eRob_SOEM_linux#2] opened 2024-12-04 20:49 UTC
Hello I figured out how to run the motor with the erob_test.cpp code. However sometimes with the same input and with the same code the motor runs for a few seconds lets say 5 secs and other time it runs for 10 secs etc. (seems like it losses the connection maybe) there seems to inconsistency. What could be the reason? Also the erob_test is in profile velocity mode. Can you give me a code example of cyclic synchronous torque mode or cyclic synchronous position mode? Please

This is the output that I get when the motor runs for some seconds and suddenly stops: 

Slave 1: Type 168530, Address 0x1001, State Machine actual 8, required 8
Name: ZeroErr Driver
___________________________________________
__________STEP 9___________________
######################################################################################
################# All slaves entered into OP state! ##################################
 , O:Program runtime: 0h:0m:0s:921ms105usProgram runtime: 0h:0m:0s:928ms821usProgram runtime: 0h:0m:0s:930ms229usProgram runtime: 0h:0m:0s:932ms598usProgram runtime: 0h:0m:0s:934ms717usProgram runtime: 0h:0m:0s:936ms107usProgram runtime: 0h:0m:0s:937ms483usProgram runtime: 0h:0m:0s:938ms855usProgram runtime: 0h:0m:0s:940ms229usProgram runtime: 0h:0m:0s:941ms597usProgram runtime: 0h:0m:0s:943ms214usProgram runtime: 0h:0m:0s:944ms595usProgram runtime: 0h:0m:0s:945ms977usProgram runtime: 0h:0m:0s:947ms357usProgram runtime: 0h:0m:0s:948ms769usProgram runtime: 0h:0m:0s:950ms168usProgram runtime: 0h:0m:0s:951ms577usProgram runtime: 0h:0m:0s:953ms4usProgram runtime: 0h:0m:0s:954ms393usProgram runtime: 0h:0m:0s:955ms778usProgram runtime: 0h:0m:0s:957ms165usProgram runtime: 0h:0m:0s:958ms822usProgram runtime: 0h:0m:0s:960ms199usProgram runtime: 0h:0m:0s:961ms569usProgram runtime: 0h:0m:0s:962ms953usProgram runtime: 0h:0m:0s:964ms326usProgram runtime: 0h:0m:0s:965ms711usProgram runtime: 0h:0m:0s:967ms93usProgram runtime: 0h:0m:0s:968ms474usProgram runtime: 0h:0m:0s:969ms867usProgram runtime: 0h:0m:0s:971ms258usProgram runtime: 0h:0m:0s:972ms625usProgram runtime: 0h:0m:0s:974ms21usProgram runtime: 0h:0m:0s:975ms407usProgram runtime: 0h:0m:0s:976ms787usProgram runtime: 0h:0m:0s:978ms160usProgram runtime: 0h:0m:0s:979ms549usProgram runtime: 0h:0m:0s:980ms928usProgram runtime: 0h:0m:0s:982ms299usProgram runtime: 0h:0m:0s:983ms675usProgram runtime: 0h:0m:0s:985ms43usProgram runtime: 0h:0m:0s:986ms461usProgram runtime: 0h:0m:0s:987ms848usProgram runtime: 0h:0m:0s:989ms471usProgram runtime: 0h:0m:0s:990ms861usProgram runtime: 0h:0m:0s:992ms248usProgram runtime: 0h:0m:0s:993ms882usProgram runtime: 0h:0m:0s:995ms252usProgram runtime: 0h:0m:0s:996ms642usProgram runtime: 0h:0m:0s:998ms13usProgram runtime: 0h:0m:0s:999ms388usProgram runtime: 0h:0m:1s:0ms708usProgram runtime: 0h:0m:1s:2ms82us

**Comment by Rohithossain007** [comment] 2024-12-04 21:01
Just let me know what I need to study or do in the code to get consistent result. Like if I want to run it for 5 secs it should run it for 5 secs only. While getting the motor in operational mode worked fine thank you for that.

**Comment by ZeroErrControl** [comment] 2024-12-05 01:48
> Just let me know what I need to study or do in the code to get consistent result. Like if I want to run it for 5 secs it should run it for 5 secs only. While getting the motor in operational mode worked fine thank you for that.

Thank you for reporting this issue.

The problem you described is caused by system latency or insufficient real-time performance, which affects stable communication between the master and slaves.

Even with RTLinux, we recommend running the following command to verify if the maximum scheduling latency exceeds millisecond-level ranges:

```sudo cyclictest -m -p99 -t1 -i100 -a3```

In a similar case with Jetson Nano (without RTLinux), we achieved 4 hours of stable testing through the following optimizations:

Reducing system latency: Disable unnecessary tasks to lower system load.
Maximizing system performance: Ensure all cores are running at maximum frequency.
Kernel isolation: Bind EtherCAT tasks to specific CPU cores to avoid interference.
Regarding error tolerance, EtherCAT's strict real-time requirements mean that system latency-induced disconnections cannot be resolved by adjusting error thresholds. Instead, we recommend focusing on optimizing system performance and resource allocation.

**Comment by Rohithossain007** [comment] 2024-12-05 04:09
Thank you very much I Gotcha, will try that and get back to you. Also can you tell me what should I do to achieve cyclic synchronous torque mode?

**Comment by ZeroErrControl** [comment] 2024-12-05 05:42
You can first refer to the relevant sections of our company's ***eRob CANopen and EtherCAT User Manual***. We follow the step-by-step instructions outlined in the manual to implement each mode. [ere is the download link](https://en.zeroerr.cn/support/download/manual)

**Comment by ZeroErrControl** [comment] 2024-12-06 07:33
> Hello I figured out how to run the motor with the erob_test.cpp code. However sometimes with the same input and with the same code the motor runs for a few seconds lets say 5 secs and other time it runs for 10 secs etc. (seems like it losses the connection maybe) there seems to inconsistency. What could be the reason? Also the erob_test is in profile velocity mode. Can you give me a code example of cyclic synchronous torque mode or cyclic synchronous position mode? Please
> 
> This is the output that I get when the motor runs for some seconds and suddenly stops:
> 
> Slave 1: Type 168530, Address 0x1001, State Machine actual 8, required 8 Name: ZeroErr Driver
> 
> **STEP 9**_________ ###################################################################################### ################# All slaves entered into OP state! ################################## , O:Program runtime: 0h:0m:0s:921ms105usProgram runtime: 0h:0m:0s:928ms821usProgram runtime: 0h:0m:0s:930ms229usProgram runtime: 0h:0m:0s:932ms598usProgram runtime: 0h:0m:0s:934ms717usProgram runtime: 0h:0m:0s:936ms107usProgram runtime: 0h:0m:0s:937ms483usProgram runtime: 0h:0m:0s:938ms855usProgram runtime: 0h:0m:0s:940ms229usProgram runtime: 0h:0m:0s:941ms597usProgram runtime: 0h:0m:0s:943ms214usProgram runtime: 0h:0m:0s:944ms595usProgram runtime: 0h:0m:0s:945ms977usProgram runtime: 0h:0m:0s:947ms357usProgram runtime: 0h:0m:0s:948ms769usProgram runtime: 0h:0m:0s:950ms168usProgram runtime: 0h:0m:0s:951ms577usProgram runtime: 0h:0m:0s:953ms4usProgram runtime: 0h:0m:0s:954ms393usProgram runtime: 0h:0m:0s:955ms778usProgram runtime: 0h:0m:0s:957ms165usProgram runtime: 0h:0m:0s:958ms822usProgram runtime: 0h:0m:0s:960ms199usProgram runtime: 0h:0m:0s:961ms569usProgram runtime: 0h:0m:0s:962ms953usProgram runtime: 0h:0m:0s:964ms326usProgram runtime: 0h:0m:0s:965ms711usProgram runtime: 0h:0m:0s:967ms93usProgram runtime: 0h:0m:0s:968ms474usProgram runtime: 0h:0m:0s:969ms867usProgram runtime: 0h:0m:0s:971ms258usProgram runtime: 0h:0m:0s:972ms625usProgram runtime: 0h:0m:0s:974ms21usProgram runtime: 0h:0m:0s:975ms407usProgram runtime: 0h:0m:0s:976ms787usProgram runtime: 0h:0m:0s:978ms160usProgram runtime: 0h:0m:0s:979ms549usProgram runtime: 0h:0m:0s:980ms928usProgram runtime: 0h:0m:0s:982ms299usProgram runtime: 0h:0m:0s:983ms675usProgram runtime: 0h:0m:0s:985ms43usProgram runtime: 0h:0m:0s:986ms461usProgram runtime: 0h:0m:0s:987ms848usProgram runtime: 0h:0m:0s:989ms471usProgram runtime: 0h:0m:0s:990ms861usProgram runtime: 0h:0m:0s:992ms248usProgram runtime: 0h:0m:0s:993ms882usProgram runtime: 0h:0m:0s:995ms252usProgram runtime: 0h:0m:0s:996ms642usProgram runtime: 0h:0m:0s:998ms13usProgram runtime: 0h:0m:0s:999ms388usProgram runtime: 0h:0m:1s:0ms708usProgram runtime: 0h:0m:1s:2ms82us

Currently, we have removed the CPU affinity binding for Thread 1 and Thread 2 in the new program （eRob_test.cpp） to avoid unpredictable scheduling delays. After making this adjustment, we tested the program on the RT Linux system to drive six eRob units, and it has successfully run stably for over one hour. We recommend testing the long-term enabling of eRob first. If the issue of dropping out of OP still occurs, I will further optimize the master program.

**Comment by Rohithossain007** [comment] 2024-12-06 07:36
Thank you very much I will test it on my motor tomorrow and will give you feedbacks on it.

**Comment by Rohithossain007** [comment] 2024-12-06 22:20
> > Hello I figured out how to run the motor with the erob_test.cpp code. However sometimes with the same input and with the same code the motor runs for a few seconds lets say 5 secs and other time it runs for 10 secs etc. (seems like it losses the connection maybe) there seems to inconsistency. What could be the reason? Also the erob_test is in profile velocity mode. Can you give me a code example of cyclic synchronous torque mode or cyclic synchronous position mode? Please
> > This is the output that I get when the motor runs for some seconds and suddenly stops:
> > Slave 1: Type 168530, Address 0x1001, State Machine actual 8, required 8 Name: ZeroErr Driver
> > **STEP 9**_________ ###################################################################################### ################# All slaves entered into OP state! ################################## , O:Program runtime: 0h:0m:0s:921ms105usProgram runtime: 0h:0m:0s:928ms821usProgram runtime: 0h:0m:0s:930ms229usProgram runtime: 0h:0m:0s:932ms598usProgram runtime: 0h:0m:0s:934ms717usProgram runtime: 0h:0m:0s:936ms107usProgram runtime: 0h:0m:0s:937ms483usProgram runtime: 0h:0m:0s:938ms855usProgram runtime: 0h:0m:0s:940ms229usProgram runtime: 0h:0m:0s:941ms597usProgram runtime: 0h:0m:0s:943ms214usProgram runtime: 0h:0m:0s:944ms595usProgram runtime: 0h:0m:0s:945ms977usProgram runtime: 0h:0m:0s:947ms357usProgram runtime: 0h:0m:0s:948ms769usProgram runtime: 0h:0m:0s:950ms168usProgram runtime: 0h:0m:0s:951ms577usProgram runtime: 0h:0m:0s:953ms4usProgram runtime: 0h:0m:0s:954ms393usProgram runtime: 0h:0m:0s:955ms778usProgram runtime: 0h:0m:0s:957ms165usProgram runtime: 0h:0m:0s:958ms822usProgram runtime: 0h:0m:0s:960ms199usProgram runtime: 0h:0m:0s:961ms569usProgram runtime: 0h:0m:0s:962ms953usProgram runtime: 0h:0m:0s:964ms326usProgram runtime: 0h:0m:0s:965ms711usProgram runtime: 0h:0m:0s:967ms93usProgram runtime: 0h:0m:0s:968ms474usProgram runtime: 0h:0m:0s:969ms867usProgram runtime: 0h:0m:0s:971ms258usProgram runtime: 0h:0m:0s:972ms625usProgram runtime: 0h:0m:0s:974ms21usProgram runtime: 0h:0m:0s:975ms407usProgram runtime: 0h:0m:0s:976ms787usProgram runtime: 0h:0m:0s:978ms160usProgram runtime: 0h:0m:0s:979ms549usProgram runtime: 0h:0m:0s:980ms928usProgram runtime: 0h:0m:0s:982ms299usProgram runtime: 0h:0m:0s:983ms675usProgram runtime: 0h:0m:0s:985ms43usProgram runtime: 0h:0m:0s:986ms461usProgram runtime: 0h:0m:0s:987ms848usProgram runtime: 0h:0m:0s:989ms471usProgram runtime: 0h:0m:0s:990ms861usProgram runtime: 0h:0m:0s:992ms248usProgram runtime: 0h:0m:0s:993ms882usProgram runtime: 0h:0m:0s:995ms252usProgram runtime: 0h:0m:0s:996ms642usProgram runtime: 0h:0m:0s:998ms13usProgram runtime: 0h:0m:0s:999ms388usProgram runtime: 0h:0m:1s:0ms708usProgram runtime: 0h:0m:1s:2ms82us
> 
> Currently, we have removed the CPU affinity binding for Thread 1 and Thread 2 in the new program （eRob_test.cpp） to avoid unpredictable scheduling delays. After making this adjustment, we tested the program on the RT Linux system to drive 6 eRobs, and it has successfully run stably for over 3 hours. We recommend testing the long-term enabling of eRob first. If the issue of dropping out of OP still occurs, I will further optimize the master program.

hey I tried the code. I tested it for 10 mins and more it works perfectly fine however if you increase the velocity sometimes it fails, It gave me failure one/two times trying to recreate it will show you if I could otherwise I will close this issue because that much speed should not be an issue. But I would suggest try the code with increased velocity. I am still testing will keep you updated.

**Comment by Rohithossain007** [comment] 2024-12-06 22:52
yeap recreated the error. So after some time with velocity of -15000 or 15000 I get the same error. Although I tried with 12000 it works fine it also works fine with 13000. For me 12000 works though so not too much important but do look into it sometimes. I am guessing to much current buildup is causing the issue.

################# All slaves entered into OP state! ##################################
 , O:Program runtime: 0h:1m:59s:485ms948usProgram runtime: 0h:1m:59s:488ms151usProgram runtime: 0h:1m:59s:489ms271usProgram runtime: 0h:1m:59s:490ms374usProgram runtime: 0h:1m:59s:491ms719usProgram runtime: 0h:1m:59s:492ms828usProgram runtime: 0h:1m:59s:493ms935usProgram runtime: 0h:1m:59s:495ms36usProgram runtime: 0h:1m:59s:496ms140usProgram runtime: 0h:1m:59s:497ms240usProgram runtime: 0h:1m:59s:498ms352usProgram runtime: 0h:1m:59s:499ms712usProgram runtime: 0h:1m:59s:500ms809usProgram runtime: 0h:1m:59s:501ms906usProgram runtime: 0h:1m:59s:503ms6usProgram runtime: 0h:1m:59s:504ms122usProgram runtime: 0h:1m:59s:505ms253usProgram runtime: 0h:1m:59s:506ms388usProgram runtime: 0h:1m:59s:507ms732usProgram runtime: 0h:1m:59s:508ms825usProgram runtime: 0h:1m:59s:509ms938usProgram runtime: 0h:1m:59s:511ms44usProgram runtime: 0h:1m:59s:512ms151usProgram runtime: 0h:1m:59s:513ms250usProgram runtime: 0h:1m:59s:514ms351usProgram runtime: 0h:1m:59s:515ms471us

**Comment by Rohithossain007** [comment] 2024-12-06 22:55
Next I will try to do the torque mode and will try to optimize the code if possible and let you know. is there any other prefered method you would love to talk? or git hub is fine?

**Comment by Rohithossain007** [comment] 2024-12-06 23:24
I have added reading actual position of each slaves  
[eRob_test.txt](https://github.com/user-attachments/files/18044932/eRob_test.txt)

**Comment by ZeroErrControl** [comment] 2024-12-09 00:54
> I have added reading actual position of each slaves [eRob_test.txt](https://github.com/user-attachments/files/18044964/eRob_test.txt)


I suggest you submit a pull request for this code. If you have further optimizations or functional enhancements in the future, you are welcome to continue submitting pull requests. We will provide you with a discount coupon for purchasing products as support.

**Comment by ZeroErrControl** [comment] 2024-12-09 00:58
> yeap recreated the error. So after some time with velocity of -15000 or 15000 I get the same error. Although I tried with 12000 it works fine it also works fine with 13000. For me 12000 works though so not too much important but do look into it sometimes. I am guessing to much current buildup is causing the issue.
> 
> ################# All slaves entered into OP state! ################################## , O:Program runtime: 0h:1m:59s:485ms948usProgram runtime: 0h:1m:59s:488ms151usProgram runtime: 0h:1m:59s:489ms271usProgram runtime: 0h:1m:59s:490ms374usProgram runtime: 0h:1m:59s:491ms719usProgram runtime: 0h:1m:59s:492ms828usProgram runtime: 0h:1m:59s:493ms935usProgram runtime: 0h:1m:59s:495ms36usProgram runtime: 0h:1m:59s:496ms140usProgram runtime: 0h:1m:59s:497ms240usProgram runtime: 0h:1m:59s:498ms352usProgram runtime: 0h:1m:59s:499ms712usProgram runtime: 0h:1m:59s:500ms809usProgram runtime: 0h:1m:59s:501ms906usProgram runtime: 0h:1m:59s:503ms6usProgram runtime: 0h:1m:59s:504ms122usProgram runtime: 0h:1m:59s:505ms253usProgram runtime: 0h:1m:59s:506ms388usProgram runtime: 0h:1m:59s:507ms732usProgram runtime: 0h:1m:59s:508ms825usProgram runtime: 0h:1m:59s:509ms938usProgram runtime: 0h:1m:59s:511ms44usProgram runtime: 0h:1m:59s:512ms151usProgram runtime: 0h:1m:59s:513ms250usProgram runtime: 0h:1m:59s:514ms351usProgram runtime: 0h:1m:59s:515ms471us

Great testing! I will follow your suggestions and give it a try. If the issue of dropping out of OP during operation persists, we will continue to improve the code.

**Comment by wdb-123** [comment] 2024-12-09 01:00
> Next I will try to do the torque mode and will try to optimize the code if possible and let you know. is there any other prefered method you would love to talk? or git hub is fine?

wechat？

**Comment by Rohithossain007** [comment] 2024-12-09 18:25
> > Next I will try to do the torque mode and will try to optimize the code if possible and let you know. is there any other prefered method you would love to talk? or git hub is fine?
> 
> wechat？

yes wechat sounds good let me know how can I connect.

**Comment by Rohithossain007** [comment] 2024-12-09 18:44
> > yeap recreated the error. So after some time with velocity of -15000 or 15000 I get the same error. Although I tried with 12000 it works fine it also works fine with 13000. For me 12000 works though so not too much important but do look into it sometimes. I am guessing to much current buildup is causing the issue.
> > ################# All slaves entered into OP state! ################################## , O:Program runtime: 0h:1m:59s:485ms948usProgram runtime: 0h:1m:59s:488ms151usProgram runtime: 0h:1m:59s:489ms271usProgram runtime: 0h:1m:59s:490ms374usProgram runtime: 0h:1m:59s:491ms719usProgram runtime: 0h:1m:59s:492ms828usProgram runtime: 0h:1m:59s:493ms935usProgram runtime: 0h:1m:59s:495ms36usProgram runtime: 0h:1m:59s:496ms140usProgram runtime: 0h:1m:59s:497ms240usProgram runtime: 0h:1m:59s:498ms352usProgram runtime: 0h:1m:59s:499ms712usProgram runtime: 0h:1m:59s:500ms809usProgram runtime: 0h:1m:59s:501ms906usProgram runtime: 0h:1m:59s:503ms6usProgram runtime: 0h:1m:59s:504ms122usProgram runtime: 0h:1m:59s:505ms253usProgram runtime: 0h:1m:59s:506ms388usProgram runtime: 0h:1m:59s:507ms732usProgram runtime: 0h:1m:59s:508ms825usProgram runtime: 0h:1m:59s:509ms938usProgram runtime: 0h:1m:59s:511ms44usProgram runtime: 0h:1m:59s:512ms151usProgram runtime: 0h:1m:59s:513ms250usProgram runtime: 0h:1m:59s:514ms351usProgram runtime: 0h:1m:59s:515ms471us
> 
> Great testing! I will follow your suggestions and give it a try. If the issue of dropping out of OP during operation persists, we will continue to improve the code.

Thank you very much

**Comment by Rohithossain007** [comment] 2024-12-11 22:12
> Great testing! I will follow your suggestions and give it a try. If the issue of dropping out of OP during operation persists, we will continue to improve the code.

hey so I have been trying to get the motor into csp mode. So i changed the mode from 9 to 8. Then this is what I got am I missing something? :         

        uint8    operation_mode = 8;
        for (int i = 1; i <= ec_slavecount; i++) {
            ec_SDOwrite(i, 0x6040, 0x00, FALSE, sizeof(Control_Word), &Control_Word, 5*EC_TIMEOUTSAFE);
            ec_SDOwrite(i, 0x6060, 0x00, FALSE, sizeof(operation_mode), &operation_mode, EC_TIMEOUTSAFE);
        }
        // Record start time

        auto start = std::chrono::high_resolution_clock::now();
        //osal_usleep(1000000);
        int step = 0;
        for(i = 1; i <= 3*60*60*1000; i++)
        {

            ec_send_processdata();
            wkc = ec_receive_processdata(EC_TIMEOUTRET);

            if(wkc >= expectedWKC)
            {
               printf("\n Processdata cycle %4d, WKC %d \r , O:", i, wkc);
               needlf = TRUE;
            }

            uint32_t target_position = 100; //
            uint32_t target_velocity = 1200; //
            uint16 output_data[10] = {0};
            if (step > 600)
            {

                output_data[0] = target_position & 0x607A;       //
                output_data[1] = (target_position >> 16) & 0x607A; //
                output_data[2] = 0x00;          //
                output_data[3] = 0x00; //
                output_data[4] = target_velocity & 0x60FF;          //
                output_data[5] = (target_velocity >> 16) & 0x60FF; //
                output_data[6] = 0x00; //
                output_data[7] = 0x00; //
                output_data[8] = 0x00; //
                output_data[9] = 0x0f; //

                //step = 1;
            }
            if (step <= 600 && step > 400)
            {

                output_data[0] = target_position & 0x607A;          //
                output_data[1] = (target_position >> 16) & 0x607A; //
                output_data[2] = 0x00;          //
                output_data[3] = 0x00; //
                output_data[4] = target_velocity & 0x60FF;          //
                output_data[5] = (target_velocity >> 16) & 0x60FF; //
                output_data[6] = 0x00; //
                output_data[7] = 0x00; //
                output_data[8] = 0x00; //
                output_data[9] = 0x07; //
               // memcpy(ec_slave[0].outputs, output_data, sizeof(output_data)); //
                //step = 3;

            }
            if (step <= 400 && step >200 )
            {

                output_data[0] = target_position & 0x607A;          //
                output_data[1] = (target_position >> 16) & 0x607A; //
                output_data[2] = 0x00;          //
                output_data[3] = 0x00; //
                output_data[4] = 0x00;          //
                output_data[5] = 0x00; //
                output_data[6] = 0x00; //
                output_data[7] = 0x00; //
                output_data[8] = 0x00; //
                output_data[9] = 0x06; //
               // memcpy(ec_slave[0].outputs, output_data, sizeof(output_data)); //
                //step = 2;
            }
            if (step <= 200)
            {
                output_data[0] = target_position & 0x607A;          //
                output_data[1] = (target_position >> 16) & 0x607A; //
                output_data[2] = 0x00;          //
                output_data[3] = 0x00; //
                output_data[4] = 0x00;          //
                output_data[5] = 0x00; //
                output_data[6] = 0x00; //
                output_data[7] = 0x00; //
                output_data[8] = 0x00; //
                output_data[9] = 0xf0; //
                //memcpy(ec_slave[0].outputs, output_data, sizeof(output_data)); //
            }

**Comment by ZeroErrControl** [comment] 2024-12-12 03:31
> > Great testing! I will follow your suggestions and give it a try. If the issue of dropping out of OP during operation persists, we will continue to improve the code.
> 
> hey so I have been trying to get the motor into csp mode. So i changed the mode from 9 to 8. Then this is what I got am I missing something? :
> 
> ```
>     uint8    operation_mode = 8;
>     for (int i = 1; i <= ec_slavecount; i++) {
>         ec_SDOwrite(i, 0x6040, 0x00, FALSE, sizeof(Control_Word), &Control_Word, 5*EC_TIMEOUTSAFE);
>         ec_SDOwrite(i, 0x6060, 0x00, FALSE, sizeof(operation_mode), &operation_mode, EC_TIMEOUTSAFE);
>     }
>     // Record start time
> 
>     auto start = std::chrono::high_resolution_clock::now();
>     //osal_usleep(1000000);
>     int step = 0;
>     for(i = 1; i <= 3*60*60*1000; i++)
>     {
> 
>         ec_send_processdata();
>         wkc = ec_receive_processdata(EC_TIMEOUTRET);
> 
>         if(wkc >= expectedWKC)
>         {
>            printf("\n Processdata cycle %4d, WKC %d \r , O:", i, wkc);
>            needlf = TRUE;
>         }
> 
>         uint32_t target_position = 100; //
>         uint32_t target_velocity = 12000; //
>         uint16 output_data[10] = {0};
>         if (step > 600)
>         {
> 
>             output_data[0] = target_position & 0x607A;       //
>             output_data[1] = (target_position >> 16) & 0x607A; //
>             output_data[2] = 0x00;          //
>             output_data[3] = 0x00; //
>             output_data[4] = target_velocity & 0x60FF;          //
>             output_data[5] = (target_velocity >> 16) & 0x60FF; //
>             output_data[6] = 0x00; //
>             output_data[7] = 0x00; //
>             output_data[8] = 0x00; //
>             output_data[9] = 0x0f; //
> 
>             //step = 1;
>         }
>         if (step <= 600 && step > 400)
>         {
> 
>             output_data[0] = target_position & 0x607A;          //
>             output_data[1] = (target_position >> 16) & 0x607A; //
>             output_data[2] = 0x00;          //
>             output_data[3] = 0x00; //
>             output_data[4] = target_velocity & 0x60FF;          //
>             output_data[5] = (target_velocity >> 16) & 0x60FF; //
>             output_data[6] = 0x00; //
>             output_data[7] = 0x00; //
>             output_data[8] = 0x00; //
>             output_data[9] = 0x07; //
>            // memcpy(ec_slave[0].outputs, output_data, sizeof(output_data)); //
>             //step = 3;
> 
>         }
>         if (step <= 400 && step >200 )
>         {
> 
>             output_data[0] = target_position & 0x607A;          //
>             output_data[1] = (target_position >> 16) & 0x607A; //
>             output_data[2] = 0x00;          //
>             output_data[3] = 0x00; //
>             output_data[4] = 0x00;          //
>             output_data[5] = 0x00; //
>             output_data[6] = 0x00; //
>             output_data[7] = 0x00; //
>             output_data[8] = 0x00; //
>             output_data[9] = 0x06; //
>            // memcpy(ec_slave[0].outputs, output_data, sizeof(output_data)); //
>             //step = 2;
>         }
>         if (step <= 200)
>         {
>             output_data[0] = target_position & 0x607A;          //
>             output_data[1] = (target_position >> 16) & 0x607A; //
>             output_data[2] = 0x00;          //
>             output_data[3] = 0x00; //
>             output_data[4] = 0x00;          //
>             output_data[5] = 0x00; //
>             output_data[6] = 0x00; //
>             output_data[7] = 0x00; //
>             output_data[8] = 0x00; //
>             output_data[9] = 0xf0; //
>             //memcpy(ec_slave[0].outputs, output_data, sizeof(output_data)); //
>         }
> ```

When using CSP mode, the system requires high real-time performance. To avoid exceeding the speed error limits, a motion planning algorithm must be added before sending the target position to eRob. Directly sending the target position without planning can cause abrupt changes, leading to excessive speed errors or triggering alarms.

If you wish to test CSP mode, it is recommended to incrementally increase the target position based on eRob's current position, for example, by adding 0-100 pulses at a time. This approach effectively controls the change in target position, prevents speed error from exceeding limits, and allows you to verify the system's real-time performance and responsiveness.

**Comment by Rohithossain007** [comment] 2024-12-12 04:01
So you are saying I should keep my actual position as target position at first and then increment it slowly? Otherwise all other things are okay?

**Comment by ZeroErrControl** [comment] 2024-12-12 05:58
> You can first refer to the relevant sections of our company's _**eRob CANopen and EtherCAT User Manual**_. We follow the step-by-step instructions outlined in the manual to implement each mode. [Here is the download link](https://en.zeroerr.cn/support/download/manual)


Yes, that's correct. Apart from that, there are no other issues. You can try using this demo to test the CSP mode, but the overall code still needs optimization.

**Comment by Rohithossain007** [comment] 2024-12-12 06:00
> > You can first refer to the relevant sections of our company's _**eRob CANopen and EtherCAT User Manual**_. We follow the step-by-step instructions outlined in the manual to implement each mode. [Here is the download link](https://en.zeroerr.cn/support/download/manual)
> 
> 
> 
> 
> 
> Yes, that's correct. Apart from that, there are no other issues. You can try using this demo to test the CSP mode, but the overall code still needs optimization.

Thank you I will try that and let you know. Maybe tomorrow or Day after tomorrow. Have a great day.

**Comment by Rohithossain007** [comment] 2024-12-13 21:17
> > You can first refer to the relevant sections of our company's _**eRob CANopen and EtherCAT User Manual**_. We follow the step-by-step instructions outlined in the manual to implement each mode. [Here is the download link](https://en.zeroerr.cn/support/download/manual)
> 
> Yes, that's correct. Apart from that, there are no other issues. You can try using this demo to test the CSP mode, but the overall code still needs optimization.


Hey I tried giving pulse there with 50 but it was still not working. Something hit my mind you mentioned high real time performance is that the main thing that I should be looking forward. Did you mean that I should use PreeMPT here? (Since I am working with linux) or you are suggesting something different? For now this is my code: 

            int32_t actual_position = 0;
            uint32_t target_position = 0;
            const int32_t increment = 50; 
            uint8_t actual_position_sdo[4] = {0};

                int rdl = sizeof(actual_position_sdo);
                int ret = ec_SDOread(1, 0x6064, 0x00, FALSE, &rdl, actual_position_sdo, EC_TIMEOUTSAFE);
                if (ret > 0) {
                    actual_position = *(int32_t*)actual_position_sdo;
                    target_position = (uint32_t)(actual_position + increment);
                    printf("target position %d", target_position);
        uint32_t target_velocity = 12000;
        uint16 output_data[10] = {0};
        if (step > 600)
        {

            output_data[0] = target_position & 0x607A;       //
            output_data[1] = (target_position >> 16) & 0x607A; //
            output_data[2] = 0x00;          //
            output_data[3] = 0x00; //
            output_data[4] = target_velocity & 0x60FF;          //
            output_data[5] = (target_velocity >> 16) & 0x60FF; //
            output_data[6] = 0x00; //
            output_data[7] = 0x00; //
            output_data[8] = 0x00; //
            output_data[9] = 0x0f; //

            //step = 1;
        }

**Comment by Rohithossain007** [comment] 2024-12-13 21:45
Should I create a new issue for CSP mode and close this one since it is already solved? Or are you comfortable talking here?

**Comment by ZeroErrControl** [comment] 2024-12-14 02:41
> Should I create a new issue for CSP mode and close this one since it is already solved? Or are you comfortable talking here?

create a new issue for CSP mode

**Comment by ZeroErrControl** [comment] 2024-12-14 02:46
> > > You can first refer to the relevant sections of our company's _**eRob CANopen and EtherCAT User Manual**_. We follow the step-by-step instructions outlined in the manual to implement each mode. [Here is the download link](https://en.zeroerr.cn/support/download/manual)
> > 
> > 
> > Yes, that's correct. Apart from that, there are no other issues. You can try using this demo to test the CSP mode, but the overall code still needs optimization.
> 
> Hey I have downloaded the manual and I tried giving pulse there with 50 but it was still not working. Something hit my mind you mentioned high real time performance is that the main thing that I should be looking forward. Did you mean that I should use PreeMPT here? (Since I am working with linux) or you are suggesting something different? For now this is my code:
> 
> ```
>         int32_t actual_position = 0;
>         uint32_t target_position = 0;
>         const int32_t increment = 50; 
>         uint8_t actual_position_sdo[4] = {0};
> 
>             int rdl = sizeof(actual_position_sdo);
>             int ret = ec_SDOread(1, 0x6064, 0x00, FALSE, &rdl, actual_position_sdo, EC_TIMEOUTSAFE);
>             if (ret > 0) {
>                 actual_position = *(int32_t*)actual_position_sdo;
>                 target_position = (uint32_t)(actual_position + increment);
>                 printf("target position %d", target_position);
>     uint32_t target_velocity = 12000;
>     uint16 output_data[10] = {0};
>     if (step > 600)
>     {
> 
>         output_data[0] = target_position & 0x607A;       //
>         output_data[1] = (target_position >> 16) & 0x607A; //
>         output_data[2] = 0x00;          //
>         output_data[3] = 0x00; //
>         output_data[4] = target_velocity & 0x60FF;          //
>         output_data[5] = (target_velocity >> 16) & 0x60FF; //
>         output_data[6] = 0x00; //
>         output_data[7] = 0x00; //
>         output_data[8] = 0x00; //
>         output_data[9] = 0x0f; //
> 
>         //step = 1;
>     }
> ```

I will start attempt to drive eRob using the CSP (Cyclic Synchronous Position) mode. I will provide feedback after the test. Please create a new issue.

**Comment by Rohithossain007** [comment] 2024-12-14 02:51
> using

Thank you very much. I am closing this one and creating a new issue.

**Closed** 2024-12-14 02:51 UTC
